### ISSUE TITLE
[Support] Event of UZTimebar

### ISSUE THREAD

**Issue by hongnguyenpro** [uizaio/uiza-android-sdk-player#47]
How can I get event of buffer data from UZTimebar?

**Comment by hongnguyenpro** [comment]
So, please remove the invisible border around seekbar.

**Comment by tplloi** [comment]
Hi,
Update vs ```2.7.4``` and run module sample to understand how to use ```setProgressCallback()```
Prefer to ```https://github.com/uizaio/uiza-android-sdk-player/blob/dev/sample/src/main/java/testlibuiza/sample/v3/uzv3/UZPlayerActivity.java``` for more details.
Btw, can you give me the photo of `an invisible border around seekbar`?

**Comment by hongnguyenpro** [comment]
Hi,
I have just update an image which contains 2 seekbar for video player, one is UZTimebar (above) and 
our SeekBar (below), how can I make current UZTimebar of Player like our SeekBar?
![device-2018-11-06-134056](https://user-images.githubusercontent.com/3148376/48047154-b4a21f80-e1c9-11e8-89f1-4275c509a4d8.png)

**Comment by tplloi** [comment]
Read lasted [change log](https://github.com/uizaio/uiza-android-sdk-player/blob/master/CHANGELOG.md)
